stages:
  - linting
  - test

linting:
  stage: linting
  image: registry.gitlab.com/it-telegram/telegram_channels_parser:latest
  script:
    - flake8 .

test:
  stage: test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo ""
  script:
    - docker-compose -f docker-compose.test.yml up --exit-code-from fastapi
  after_script:
    - docker-compose -f docker-compose.test.yml down