"""database create

Revision ID: 6a5d63453be7
Revises: 
Create Date: 2023-10-01 20:19:27.189926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5d63453be7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_info_id'), 'channel_info', ['id'], unique=False)
    op.create_index(op.f('ix_channel_info_username'), 'channel_info', ['username'], unique=True)
    op.create_table('latest_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('forwards', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('reactions', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latest_messages_channel_id'), 'latest_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_latest_messages_id'), 'latest_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_latest_messages_id'), table_name='latest_messages')
    op.drop_index(op.f('ix_latest_messages_channel_id'), table_name='latest_messages')
    op.drop_table('latest_messages')
    op.drop_index(op.f('ix_channel_info_username'), table_name='channel_info')
    op.drop_index(op.f('ix_channel_info_id'), table_name='channel_info')
    op.drop_table('channel_info')
    # ### end Alembic commands ###
