"""database update

Revision ID: bdf049c6c73f
Revises: 6a5d63453be7
Create Date: 2023-10-02 00:44:01.443919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf049c6c73f'
down_revision: Union[str, None] = '6a5d63453be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('latest_messages', sa.Column('channel_username', sa.String(), nullable=True))
    op.drop_index('ix_latest_messages_channel_id', table_name='latest_messages')
    op.create_index(op.f('ix_latest_messages_channel_username'), 'latest_messages', ['channel_username'], unique=False)
    op.drop_constraint('latest_messages_channel_id_fkey', 'latest_messages', type_='foreignkey')
    op.create_foreign_key(None, 'latest_messages', 'channel_info', ['channel_username'], ['username'])
    op.drop_column('latest_messages', 'message_id')
    op.drop_column('latest_messages', 'channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('latest_messages', sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('latest_messages', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'latest_messages', type_='foreignkey')
    op.create_foreign_key('latest_messages_channel_id_fkey', 'latest_messages', 'channel_info', ['channel_id'], ['id'])
    op.drop_index(op.f('ix_latest_messages_channel_username'), table_name='latest_messages')
    op.create_index('ix_latest_messages_channel_id', 'latest_messages', ['channel_id'], unique=False)
    op.drop_column('latest_messages', 'channel_username')
    # ### end Alembic commands ###
